export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PUCHESABLE = "UPDATE_PURCHESABLE";
export const LOAD_ORDER = "LOAD_ORDER";
export const FAIELD_LOADORDER = "FAIELD_LOADORDER";
export const RESET_INGREDIENT = "RESET_INGREDIENT";
